### ISSUE TITLE
home-redesign: if there's an error in the create new site dialog, all the fields get reset

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#224]
In the site manager, i click on create new site and when i select a URL that is take, all of the fields get reset to blank. They should retain their original values instead of resetting.

The problem it creates, for example, is that it says: "URL already taken" and the URL we see is "my-site-url", or, if the name is invalid for being too long, the whole thing has to be retyped in.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
The New Site / Copy Site radio button and drop down list still get reset.

**Comment by gilbert** [comment]
Fixed
