### ISSUE TITLE
ie7, deelmob: Site Manager Fails

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#245]
using ie7 on windows, go to www.deelmob.com
log in as un: ymtest5@mail.com pw: 123123
go to Site Manager
There's a js error.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
I pushed the latest version to www.deelmob.com, and site manager is still failing

**Comment by onaseef** [comment]
The issue still exists on ie7 with locale=es.  The "Active Site" line is missing.  It's initially there and the it disappears.

**Comment by gilbert** [comment]
This is an unrelated styling issue. For some strange, microsoft-y reason, if the browser window is bigger than the light-gray content area, the h2 disappears. I haven't figured out how to fix it yet.
