### ISSUE TITLE
Premium branch: Remove picture link disappeared from banner upload

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#268]
With the addition of the banner size option, the remove picture link disappears.  If you don't have an image uploaded already, and you upload one, you won't see the "Remove picture" Link. However, after you upload and save and come back, it appears.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
This problem is still happening. If I upload a picture, the remove picture link doesn't appear until I do something the refreshes the view. This happens in both the header replacement and the background image uploaders

**Comment by gilbert** [comment]
Sorry about that, fixed.
