### ISSUE TITLE
PRODUCTION BUG: Adding widget to site with no widgets fails

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#382]
If you create a new site and delete all the widgets from it so you start out with a blank site, and then attempt to add a widget, the operation fails with a javascript error.

This is a bug on production. You can try it out on www.deelmob.com though because it happens there too.

www.deelmob.com aatest29@mailinator.com 123123

I created a site JRTransport 2. It has no widgets in it.   Drop in a widget and the operatin fails. 

When you fix this, please fix it in the branch master-stable then merge that with master so we can push out the change to production ASAP without introducing all of the premium site features.

**Comment by gilbert** [comment]
Fixed on branch master-stable.

**Comment by onaseef** [comment]
It still fails as follows:   www.yomobi.com  ymtest@mail.com 123123

Drop in a widget in the empty site. It adds fine
Now click Remove Widget
Drop in a new widget, and it hangs.
